---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.postgres.label }}
  name: {{ .Values.postgres.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgres.label }}
  replicas: {{ .Values.postgres.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.label }}
    spec:
      containers:
      - name: {{ .Values.postgres.container.name }}
        image: {{ .Values.postgres.container.image.repository }}:{{ .Values.postgres.container.image.tag }}
        env:
        - name: PGDATA
          value: {{ .Values.postgres.container.env.pgdata }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.container.env.postgresdb }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.container.env.postgrespass }}
        - name: PGPASSWORD
          value: {{ .Values.postgres.container.env.pgpassword }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.container.env.postgresUser }}
        - name: PGUSER
          value: {{ .Values.postgres.container.env.pguser }}
        ports:
        - containerPort: {{ .Values.postgres.container.ports.containerPort }}
          name: {{ .Values.postgres.container.ports.name }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvc.name }}  
