apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.postgres.label }}
  name: {{ .Values.postgres.pvc.name }}
  annotations:
    appuio.ch/backup: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
